# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'crop_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import cv2
import numpy as np
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QImage, QPixmap


class Crop_Form(object):
    def __init__(self, image):
        self.image = image
    def setupUi(self, Crop_Form):
        Crop_Form.setObjectName("Crop")
        Crop_Form.resize(417, 545)
        self.preview_image = QtWidgets.QLabel(Crop_Form)
        self.preview_image.setGeometry(QtCore.QRect(10, 60, 371, 311))
        self.preview_image.setText("")
        self.preview_image.setObjectName("preview_image")

        self.label_2 = QtWidgets.QLabel(Crop_Form)
        self.label_2.setGeometry(QtCore.QRect(160, 10, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.line = QtWidgets.QFrame(Crop_Form)
        self.line.setGeometry(QtCore.QRect(10, 390, 391, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_3 = QtWidgets.QLabel(Crop_Form)
        self.label_3.setGeometry(QtCore.QRect(10, 410, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Crop_Form)
        self.label_4.setGeometry(QtCore.QRect(10, 460, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.btn_apply = QtWidgets.QPushButton(Crop_Form)
        self.btn_apply.setGeometry(QtCore.QRect(180, 500, 93, 31))
        self.btn_apply.setObjectName("btn_apply")
        self.btn_cancel = QtWidgets.QPushButton(Crop_Form)
        self.btn_cancel.setGeometry(QtCore.QRect(290, 500, 93, 31))
        self.btn_cancel.setObjectName("btn_cancel")
        self.startX = QtWidgets.QSpinBox(Crop_Form)
        self.startX.setGeometry(QtCore.QRect(150, 410, 61, 31))
        self.startX.setMaximum(105)
        self.startX.setObjectName("startX")
        self.label_5 = QtWidgets.QLabel(Crop_Form)
        self.label_5.setGeometry(QtCore.QRect(240, 420, 55, 16))
        self.label_5.setObjectName("label_5")
        self.endX = QtWidgets.QSpinBox(Crop_Form)
        self.endX.setGeometry(QtCore.QRect(280, 410, 61, 31))
        self.endX.setObjectName("endX")
        self.startY = QtWidgets.QSpinBox(Crop_Form)
        self.startY.setGeometry(QtCore.QRect(150, 450, 61, 31))
        self.startY.setObjectName("startY")
        self.label_6 = QtWidgets.QLabel(Crop_Form)
        self.label_6.setGeometry(QtCore.QRect(240, 450, 55, 16))
        self.label_6.setObjectName("label_6")
        self.endY = QtWidgets.QSpinBox(Crop_Form)
        self.endY.setGeometry(QtCore.QRect(280, 450, 61, 31))
        self.endY.setObjectName("endY")

        self.retranslateUi(Crop_Form)
        QtCore.QMetaObject.connectSlotsByName(Crop_Form)

        if (len(self.image.shape) == 3) :
            w, h , c = self.image.shape
            self.endx_value = w
            self.endy_value = h
        else:
            w, h = self.image.shape
            self.endx_value = w
            self.endy_value = h
        # limit
        self.startX.setMinimum(0)
        self.startY.setMinimum(0)

        self.endX.setMaximum(self.endx_value)
        self.endY.setMaximum(self.endy_value)

        self.endX.setValue(self.endx_value)
        self.endY.setValue(self.endy_value)

        self.image = self.image[0:500, 0:500, :]
        self.image = np.transpose(self.image, (1, 0, 2)).copy()

        cv2.imshow("ssss", self.ig)
        self.updateImage()
    #     events

    def updateImage(self):
        qformat = QImage.Format_Indexed8
        if len(self.image.shape) == 3:
            if (self.image.shape[2]) == 4:
                qformat = QImage.Format_RGBA8888
            else:
                qformat = QImage.Format_RGB888
        img = QImage(self.image, self.image.shape[1], self.image.shape[0], self.image.strides[0],
                     qformat).rgbSwapped()

        self.preview_image.setPixmap(QPixmap.fromImage(img))
        self.preview_image.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.preview_image.setScaledContents(True)
    def retranslateUi(self, Crop_Form):
        _translate = QtCore.QCoreApplication.translate
        Crop_Form.setWindowTitle(_translate("Crop_Form", "Crop"))
        self.label_2.setText(_translate("Crop_Form", "Preview"))
        self.label_3.setText(_translate("Crop_Form", "X coordinate"))
        self.label_4.setText(_translate("Crop_Form", "X coordinate"))
        self.btn_apply.setText(_translate("Crop_Form", "Apply"))
        self.btn_cancel.setText(_translate("Crop_Form", "Cancel"))
        self.label_5.setText(_translate("Crop_Form", "To"))
        self.label_6.setText(_translate("Crop_Form", "To"))



