# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editvalueform.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def __init__(self, main, type):
        self.type = type
        self.main = main
    def setupUi(self, Form):
        self.Form = Form

        Form.setObjectName("Form")
        Form.resize(373, 108)
        self.slider_changeValue = QtWidgets.QSlider(Form)
        self.slider_changeValue.setGeometry(QtCore.QRect(30, 70, 211, 22))
        self.slider_changeValue.setMinimum(1)
        self.slider_changeValue.setMaximum(100)
        self.slider_changeValue.setSingleStep(2)
        self.slider_changeValue.setOrientation(QtCore.Qt.Horizontal)
        self.slider_changeValue.setObjectName("slider_changeValue")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(270, 10, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(270, 50, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.spinBox = QtWidgets.QSpinBox(Form)
        self.spinBox.setGeometry(QtCore.QRect(30, 11, 51, 41))
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(100)
        self.spinBox.setSingleStep(2)
        self.spinBox.setProperty("value", 1)
        self.spinBox.setObjectName("spinBox")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(100, 20, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.createtempValueforCancel
        #event
        self.slider_changeValue.valueChanged['int'].connect(self.changeValue)
        self.pushButton.clicked.connect(self.btnOkEvt)
        self.pushButton_2.clicked.connect(self.cancelBtnEvt)
    def createtempValueforCancel(self):
        if (self.type == 1):
            self.tmp_gaussianBlurValue = self.main.gaussianBlurValue
        elif (self.type == 2):
            self.tmp_boxBlurValue = self.main.boxBlurValue
        elif (self.type == 3):
            self.tmp_medianBlurValue = self.main.medianBlurValue
        elif (self.type == 10):
            self.spinBox.setProperty('value', self.main.c)
            self.slider_changeValue.setValue(self.main.medianBlurValue)
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "OK"))
        self.pushButton_2.setText(_translate("Form", "Cancel"))
        self.label.setText(_translate("Form", "Size"))

    def updateSpinBoxandSliderValue(self):
        if (self.type == 1):
            self.spinBox.setProperty('value', self.main.gaussianBlurValue)
            self.slider_changeValue.setValue(self.main.gaussianBlurValue)
        elif (self.type == 2):
            self.spinBox.setProperty('value', self.main.boxBlurValue)
            self.slider_changeValue.setValue(self.main.boxBlurValue)
        elif (self.type == 3):
            self.spinBox.setProperty('value', self.main.medianBlurValue)
            self.slider_changeValue.setValue(self.main.medianBlurValue)
        elif (self.type == 10):
            self.spinBox.setProperty('value', self.main.c)
            self.slider_changeValue.setValue(self.main.medianBlurValue)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        if (self.type == 1):
            Form.setWindowTitle(_translate('Gaussian Blur', 'Gaussian Blur'))
        elif (self.type == 2):
            Form.setWindowTitle(_translate('Box Blur', 'Box Blur'))
        elif (self.type == 3):
            Form.setWindowTitle(_translate('Median Blur', 'Median Blur'))
        elif (self.type == 10):
            Form.setWindowTitle(_translate('Logarit', 'Logarit'))
        self.pushButton.setText(_translate("Form", "OK"))
        self.pushButton_2.setText(_translate("Form", "Cancel"))
        self.label.setText(_translate("Form", "Size"))

    def changeValue(self, value):
        if (self.type == 1):
            self.main.gaussianBlurValue = value
        elif (self.type == 2):
            self.main.boxBlurValue = value
        elif (self.type == 3):
            self.main.medianBlurValue = value
        elif (self.type == 4):
            self.main.changeGammaValue = value
        elif (self.type == 5):
            self.main.averageBlurValue = value
        elif (self.type == 10):
            self.main.c += 1
            self.main.gamma += 1

        self.spinBox.setProperty('value', self.convertValidValue(value))
        print(self.spinBox.value())
        self.main.showImage(False)

    def btnOkEvt(self):
        self.Form.close()

    def cancelBtnEvt(self):
        if (self.type == 1):
            self.main.gaussianBlurValue = self.tmp_gaussianBlurValue
        elif (self.type == 2):
            self.main.boxBlurValue = self.tmp_boxBlurValue
        elif (self.type == 3):
            self.main.medianBlurValue = self.tmp_medianBlurValue
        self.main.showImage(False)
        self.Form.close()

    def convertValidValue(self, value):
        if value % 2 == 0:
            value += 1
        return value
