# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'giaodien.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1535, 902)
        MainWindow.setStyleSheet("background-color:#535353\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_photo = QtWidgets.QLabel(self.centralwidget)
        self.lbl_photo.setGeometry(QtCore.QRect(40, 80, 451, 701))
        self.lbl_photo.setStyleSheet("border: 1px solid black;\n"
"qproperty-alignment: AlignCenter;\n"
"background-color:white\n"
"")
        self.lbl_photo.setText("")
        self.lbl_photo.setScaledContents(True)
        self.lbl_photo.setObjectName("lbl_photo")
        self.lbl_newPhoto = QtWidgets.QLabel(self.centralwidget)
        self.lbl_newPhoto.setGeometry(QtCore.QRect(570, 80, 471, 701))
        self.lbl_newPhoto.setStyleSheet("border: 1px solid black;\n"
"qproperty-alignment: AlignCenter;\n"
"background-color:white\n"
"")
        self.lbl_newPhoto.setText("")
        self.lbl_newPhoto.setScaledContents(True)
        self.lbl_newPhoto.setObjectName("lbl_newPhoto")
        self.btn_openFIle = QtWidgets.QPushButton(self.centralwidget)
        self.btn_openFIle.setGeometry(QtCore.QRect(20, 10, 51, 41))
        self.btn_openFIle.setStyleSheet("background-color:white\n"
"")
        self.btn_openFIle.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_openFIle.setIcon(icon)
        self.btn_openFIle.setObjectName("btn_openFIle")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 60, 501, 751))
        self.label.setStyleSheet("background-color:#282828")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(540, 60, 521, 741))
        self.label_3.setStyleSheet("background-color:#282828")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(1120, 470, 331, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(1120, 440, 55, 16))
        self.label_4.setStyleSheet("color:white\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1120, 360, 91, 16))
        self.label_2.setStyleSheet("color:white\n"
"")
        self.label_2.setObjectName("label_2")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(1120, 400, 321, 22))
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(1120, 280, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet("color:white\n"
"\n"
"")
        self.checkBox.setObjectName("checkBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(1110, 60, 401, 171))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.histogramWidget = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.histogramWidget.setContentsMargins(0, 0, 0, 0)
        self.histogramWidget.setObjectName("histogramWidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(1180, 350, 261, 41))
        self.groupBox.setStyleSheet("border:none\n"
"")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.rd_btn_medium = QtWidgets.QRadioButton(self.groupBox)
        self.rd_btn_medium.setGeometry(QtCore.QRect(30, 10, 95, 20))
        self.rd_btn_medium.setStyleSheet("color:white")
        self.rd_btn_medium.setChecked(True)
        self.rd_btn_medium.setObjectName("rd_btn_medium")
        self.rd_btn_gaussian = QtWidgets.QRadioButton(self.groupBox)
        self.rd_btn_gaussian.setGeometry(QtCore.QRect(180, 10, 95, 20))
        self.rd_btn_gaussian.setStyleSheet("color:white")
        self.rd_btn_gaussian.setObjectName("rd_btn_gaussian")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(1120, 520, 71, 16))
        self.label_5.setStyleSheet("color:white\n"
"")
        self.label_5.setObjectName("label_5")
        self.slider_threshold = QtWidgets.QSlider(self.centralwidget)
        self.slider_threshold.setGeometry(QtCore.QRect(1120, 550, 331, 22))
        self.slider_threshold.setOrientation(QtCore.Qt.Horizontal)
        self.slider_threshold.setObjectName("slider_threshold")
        self.checkbox_invertImage = QtWidgets.QCheckBox(self.centralwidget)
        self.checkbox_invertImage.setGeometry(QtCore.QRect(1360, 280, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkbox_invertImage.setFont(font)
        self.checkbox_invertImage.setStyleSheet("color:white\n"
"\n"
"")
        self.checkbox_invertImage.setObjectName("checkbox_invertImage")
        self.label_3.raise_()
        self.label.raise_()
        self.lbl_photo.raise_()
        self.lbl_newPhoto.raise_()
        self.btn_openFIle.raise_()
        self.horizontalSlider.raise_()
        self.label_4.raise_()
        self.label_2.raise_()
        self.horizontalSlider_2.raise_()
        self.checkBox.raise_()
        self.verticalLayoutWidget.raise_()
        self.groupBox.raise_()
        self.label_5.raise_()
        self.slider_threshold.raise_()
        self.checkbox_invertImage.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1535, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "Brighness"))
        self.label_2.setText(_translate("MainWindow", "Blur"))
        self.checkBox.setText(_translate("MainWindow", "Ảnh xám"))
        self.rd_btn_medium.setText(_translate("MainWindow", "Trung bình"))
        self.rd_btn_gaussian.setText(_translate("MainWindow", "Gaussian"))
        self.label_5.setText(_translate("MainWindow", "Threshold"))
        self.checkbox_invertImage.setText(_translate("MainWindow", "Đảo ảnh"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
